# NOTE: update this with your service name
service: gifter-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2
  timeout: 30
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  create_user:
    handler: createUser.main
    events:
      - http:
          path: users
          method: post
          cors: true
          authorizer: aws_iam
  get_user:
    handler: getUser.main
    events: 
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
  update_user:
    handler: updateUser.main
    events: 
      - http:
          path: users
          method: put
          cors: true
          authorizer: aws_iam
  delete_user:
    handler: deleteUser.main
    events: 
      - http:
          path: users
          method: delete
          cors: true
          authorizer: aws_iam
  create_event:
    handler: createEvent.main
    events: 
      - http:
          path: events
          method: post
          cors: true
          authorizer: aws_iam
  update_event:
    handler: updateEvent.main
    events: 
      - http:
          path: events
          method: put
          cors: true
          authorizer: aws_iam  
  delete_event:
    handler: deleteEvent.main
    events: 
      - http:
          path: events
          method: delete
          cors: true
          authorizer: aws_iam       
  get_events:
      handler: getEvents.main
      events: 
        - http:
            path: events
            method: get
            cors: true
            authorizer: aws_iam 
  create_contact:
    handler: createContact.main
    events: 
      - http:
          path: contacts
          method: post
          cors: true
          authorizer: aws_iam
  update_contact:
    handler: updateContact.main
    events: 
      - http:
          path: contacts
          method: put
          cors: true
          authorizer: aws_iam     
  delete_contact:
    handler: deleteContact.main
    events: 
      - http:
          path: contacts
          method: delete
          cors: true
          authorizer: aws_iam                  
  get_contacts:
      handler: getContacts.main
      events: 
        - http:
            path: contacts
            method: get
            cors: true
            authorizer: aws_iam
  get_tags:
      handler: getTags.main
      events: 
        - http:
            path: tags
            method: get
            cors: true
            authorizer: aws_iam                              